### ISSUE TITLE
Works great!

### ISSUE THREAD

**Issue by TsurHerman** [cstjean/ClobberingReload.jl#2]
waiting for an update on warning suppression and parametric types.
thumbs up

**Comment by cstjean** [comment]
Thanks! I just updated the code to remove the redefinition warnings. You can give it a try with `Pkg.checkout("ClobberingReload")` and let me know how it goes. Parametric types will probably take a bit longer, as I don't have an immediate need for it.

**Comment by TsurHerman** [comment]
Another wild idea is to monitor the file-system continuously in a different thread and to re shove those definitions in the Main REPL frame whenever a change was detectted

**Comment by cstjean** [comment]
That's already what `@ausing` does for IJulia. Are you referring to the Julia REPL? The correct solution would be [#6445](https://github.com/JuliaLang/julia/issues/6445). Hopefully someone comes around and implements it. Using another thread might work, but it's a bit outside of my comfort zone. PRs welcome.
