### ISSUE TITLE
creload succeeds even if there are errors in reloaded modules 

### ISSUE THREAD

**Issue by TsurHerman** [cstjean/ClobberingReload.jl#6]
Hi Cedric , I have been using your package again recently , so again thank you for your time.
I have noticed that creload does not emit an error if the reloaded module contains an error.

Can this be remedied?

**Comment by cstjean** [comment]
Hi Tsur, could you please describe how to reproduce your problem? I definitely get errors when I use `creload(pkgname)` and there's anything wrong in `pkgname` (eg. syntax errors, change in type definition errors, and I just tested adding an explicit call to `error`)

**Comment by TsurHerman** [comment]
My bad, I had the creload statement hidden somewhere in a clever try catch
macro with no error handling.
Please ignore this issue.
