### ISSUE TITLE
No method matching parse_module_file(::Void)

### ISSUE THREAD

**Issue by DNF2** [cstjean/ClobberingReload.jl#9]
On Julia v0.6-rc2, tested on both `ClobberingReload` stable and master.

I have defined a module `TestMod` in a file `testmod.jl`:
```
module TestMod
x = 1
end
```
Then doing:
```
using ClobberingReload
include("testmod.jl")
using TestMod
creload("TestMod")
```
gives the following error:
```
INFO: Reloading TestMod
ERROR: MethodError: no method matching parse_module_file(::Void)
Closest candidates are:
  parse_module_file(::String) at /Users/DNF/.julia/v0.6/ClobberingReload/src/ClobberingReload.jl:27
Stacktrace:
 [1] (::ClobberingReload.##9#11{String,Void})() at /Users/DNF/.julia/v0.6/ClobberingReload/src/ClobberingReload.jl:70
 [2] withpath(::ClobberingReload.##9#11{String,Void}, ::Void) at /Users/DNF/.julia/v0.6/ClobberingReload/src/ClobberingReload.jl:51
 [3] creload(::String) at /Users/DNF/.julia/v0.6/ClobberingReload/src/ClobberingReload.jl:66
```

**Comment by cstjean** [comment]
If you replace `creload` with `reload`, it doesn't work either, so I'm not sure that it's a solvable issue. The recommended way of using modules is to `push!(LOAD_PATH, "path_to_your_module")` and name your file the same way as your module (in this case `TestMod.jl`). That way, you don't need to `include` the file - just use `using`, then `creload`.

That said, the error message could be a lot better, so I'll leave this open. 

Let me know if run into any other problem!

**Comment by DNF2** [comment]
Oh. I thought I was using it correctly. Perhaps the requirement of using `push!(LOAD_PATH, ...)` and the file naming convention should be mentioned in README?

**Comment by cstjean** [comment]
I'll make sure the error message is descriptive enough.
